import { Product } from "./types";

export const INITIAL_CATEGORIES = [
  "Todos",
  "Tecnologia",
  "Casa & Decoração",
  "Cozinha",
  "Beleza & Saúde",
  "Acessórios"
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "Fone de Ouvido Bluetooth Premium com Cancelamento de Ruído",
    description: "Desfrute de som de alta definição sem fios. Bateria de longa duração até 40 horas operacionais, microfone embutido de altíssima definição, drivers potentes e extremamente confortável para utilizar o dia todo. O campeão de vendas da Shopee pelo custo-benefício impressionante!",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
    price: 69.90,
    originalPrice: 129.90,
    link: "https://shope.ee/example-fone",
    category: "Tecnologia",
    clicks: 145,
    rating: 4.9,
    reviewsCount: 382,
    isFeatured: true,
    isAvailable: true,
    discountCode: "FONE30OFF",
    dateAdded: "2026-05-20"
  },
  {
    id: "prod-2",
    title: "Garrafa Térmica Inteligente Digital de Inox com Termômetro LED 500ml",
    description: "Mantenha sua bebida quente ou fria por até 12 horas e acompanhe a temperatura exata com um simples toque na tela LED da tampa. Feita de aço inoxidável premium livre de BPA, vedamento hermético perfeito e acabamento fosco elegante. Ideal para academia, escritório ou viagens.",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80",
    price: 24.90,
    originalPrice: 49.90,
    link: "https://shope.ee/example-garrafa",
    category: "Casa & Decoração",
    clicks: 320,
    rating: 4.8,
    reviewsCount: 1547,
    isFeatured: true,
    isAvailable: true,
    discountCode: "TEMPBARATA",
    dateAdded: "2026-05-22"
  },
  {
    id: "prod-3",
    title: "Mini Processador e Triturador de Alimentos Elétrico USB Portátil",
    description: "Triture alho, cebola, temperos e legumes em apenas 5 segundos com um simples toque! Sem fios, recarregável via USB e super fácil de limpar. Possui 3 lâminas afiadas de aço inox e copo resistente de 250ml. O utensílio mais prático e querido da cozinha moderna portuguesa e brasileira.",
    image: "https://images.unsplash.com/photo-1578643463396-0997cb5328c1?w=600&auto=format&fit=crop&q=80",
    price: 32.50,
    originalPrice: 79.90,
    link: "https://shope.ee/example-triturador",
    category: "Cozinha",
    clicks: 98,
    rating: 4.7,
    reviewsCount: 512,
    isFeatured: false,
    isAvailable: true,
    discountCode: "SHPCOZINHA",
    dateAdded: "2026-05-24"
  },
  {
    id: "prod-4",
    title: "Smartwatch Esportivo Inteligente com Sensor de Saúde e Notificações",
    description: "Monitore seus batimentos cardíacos, qualidade do sono, passos diários e receba notificações de mensagens e chamadas do WhatsApp diretamente no seu pulso. Tela touch de alta resolução, resistência à água e bateria para 7 dias. Um relógio excelente com preço imbatível de afiliado Shopee.",
    image: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=600&auto=format&fit=crop&q=80",
    price: 89.90,
    originalPrice: 199.00,
    link: "https://shope.ee/example-watch",
    category: "Tecnologia",
    clicks: 215,
    rating: 4.6,
    reviewsCount: 742,
    isFeatured: true,
    isAvailable: true,
    discountCode: "RELOGIO10",
    dateAdded: "2026-05-25"
  },
  {
    id: "prod-5",
    title: "Umidificador e Difusor de Aromas Ultrassônico LED com Efeito de Chama",
    description: "Crie um ambiente relaxante e aconchegante com o efeito realista de chama de fogo em LED. Melhora a qualidade do ar, hidrata a pele seca e funciona perfeitamente como difusor de óleos essenciais para aromaterapia. Silencioso, desliga automaticamente quando a água acaba. Lindo para a sala de estar ou escritórios.",
    image: "https://images.unsplash.com/photo-1519183071298-a2962feb14f4?w=600&auto=format&fit=crop&q=80",
    price: 45.90,
    originalPrice: 89.90,
    link: "https://shope.ee/example-diffuser",
    category: "Casa & Decoração",
    clicks: 184,
    rating: 4.8,
    reviewsCount: 310,
    isFeatured: false,
    isAvailable: true,
    discountCode: "CHAMA20",
    dateAdded: "2026-05-26"
  },
  {
    id: "prod-6",
    title: "Organizador Giratório 360 Graus para Maquiagens e Cosméticos",
    description: "Organize todos os seus batons, pincéis, cremes e perfumes em um só lugar. Giro suave de 360 graus que facilita encontrar qualquer produto em segundos. Prateleiras totalmente ajustáveis de acrílico resistente de alta qualidade. Perfeito para economizar espaço e decorar sua penteadeira de forma moderna.",
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&auto=format&fit=crop&q=80",
    price: 39.90,
    originalPrice: 79.90,
    link: "https://shope.ee/example-organizer",
    category: "Beleza & Saúde",
    clicks: 76,
    rating: 4.9,
    reviewsCount: 184,
    isFeatured: false,
    isAvailable: true,
    discountCode: "BELLE360",
    dateAdded: "2026-05-27"
  }
];
